### ISSUE TITLE
need healthcheck script with ability to kill container in case of failure

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/appium-device#21]
moved healthcheck verification into the independent script with ability to terminate itself in case of any problem with adb, stf, appium etc

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/appium-device/pull/22

as a test scenario we can 
1. start mcloud using zebrunner/android-device:1.0-beta1 container
2. login into the any device container
3. kill appium or stf
-> device container will be terminated and should be restarted

**Comment by okamara** [comment]
Will be tested later, after 1.13

**Comment by dhreben** [comment]
I  can check after Fixed https://github.com/zebrunner/android-device/issues/24

**Comment by dhreben** [comment]
Verified.
